<a href="https://colab.research.google.com/github/rilschultz/CS167Notes/blob/main/Wellmark_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Plugging in the data to use for this will be the first step to creating

In [7]:
import sklearn
import pandas
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import neighbors
from sklearn.preprocessing import StandardScaler

from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/MyDrive/datasets/Iowahealth.csv'
health = pandas.read_csv(path)
pandas.set_option('display.max_columns', 100)
health.head()

Mounted at /content/drive

,new.ID,time,RecordedDate,Age,Gender,Race,State,Urban,Relationship,Income,Children_5,Mental.health,Immuno,Chronic,Pregnant,Smoker,Drinker,Sitting_pre_1,Sitting_post_1,Outside_pre_1,Outside_post_1,Mod_pre_1,Mod Post hrs,Vig_pre_1,Vig_pre_2,Vig_post_1,Vig_post_2,Screen_pre_1,Screen_pre_2,Screen_post_1,Screen_post_2,Distress_4,BDI Total,BAI Total,BMI,Lone_total,PSS4_total,SNI.3,WEMWBS_total,SNI_total,Work_changes,RTE_post_days_1,RTE_post_mins_1,RTE_post_intensity,Sleep_post_1,BDI_9,INTENTIONS,Vaccine_received,Sitting_pre_total,Sitting_post_total,Outside_pre_total,Outside_post_total,Screen_pre_total,Screen_post_total,BMI_range,COV_symp,COV_changes,COV_iso,COV_iso_day_4,COV_iso_guide,Guide_contact,Guide_hygiene
0,1,baseline,4/3/2020 17:41,5.0,1.0,White,South,1.0,1,5.0,2.0,NaN,3.0,2.0,NaN,2.0,1.0,3.0,5.0,1.0,1.0,0.0,0.25,0.0,25.0,0.0,30.0,8.0,0.0,9.0,0.0,2.0,1,5,24.8,3,3.0,14.0,28,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,180.0,300.0,75.0,90.0,480.0,540.0,NaN,4.0,"3,5",NaN,NaN,NaN,5,"3,8"
1,1,week1,4/11/2020 11:17,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,7.0,NaN,10.0,NaN,0.25,NaN,NaN,0.0,30.0,NaN,NaN,6.0,0.0,2.0,2,3,NaN,4,3.0,10.0,27,10,4.0,0.0,NaN,NaN,8.0,0.0,NaN,NaN,NaN,450.0,NaN,615.0,NaN,360.0,NaN,4.0,4,NaN,NaN,NaN,5,3
2,2,baseline,4/3/2020 17:46,1.0,1.0,White,Midwest,2.0,2,7.0,0.0,NaN,3.0,3.0,NaN,2.0,1.0,6.0,12.0,2.0,0.0,0.0,0,0.0,10.0,0.0,0.0,4.0,0.0,8.0,0.0,5.0,11,3,22.1,5,6.0,8.0,18,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,360.0,720.0,120.0,0.0,240.0,480.0,NaN,4.0,5,NaN,NaN,NaN,"5,6,8",2
3,2,month1,7/3/2020 22:49,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,10.0,NaN,2.0,NaN,1,NaN,NaN,4.0,0.0,NaN,NaN,12.0,0.0,6.0,11,0,NaN,3,7.0,NaN,20,10,4.0,0.0,NaN,NaN,9.0,0.0,NaN,NaN,NaN,600.0,NaN,120.0,NaN,720.0,NaN,1.0,5,NaN,NaN,NaN,8,2
4,2,month10,4/5/2021 13:09,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,8.0,NaN,2.0,NaN,4,NaN,NaN,1.0,0.0,NaN,NaN,5.0,0.0,4.0,0,6,NaN,3,3.0,NaN,28,11,4.0,0.0,NaN,NaN,8.0,0.0,NaN,2.0,NaN,480.0,NaN,120.0,NaN,300.0,NaN,4.0,NaN,NaN,NaN,NaN,6,2

In [8]:
import numpy

sub1_health = health[['new.ID', 'time', 'Age', 'Gender', 'Race', 'Urban', 'Immuno', 'Chronic', 'Smoker', 'Drinker', 'Mod Post hrs', 'BDI Total', 'BAI Total', 'BMI']]

sub1_health.count()



subset = sub1_health[sub1_health.time == 'baseline']
#incorrect_values = subset['Mod Post hrs'] != 
#subset = subset.drop(index=subset[incorrect_values].index)
subset.isna().any()
subset.Gender.value_counts(dropna = True)

subset_nomiss = subset.dropna()
subset_nomiss.isna().any()
subset_nomiss

health2 = health[health.time == 'baseline']
health2.BMI.value_counts().head(50)

25.1    86
25.8    78
26.6    63
24.4    62
23.0    54
27.4    54
23.7    53
25.7    48
24.3    41
25.0    41
21.6    34
23.4    33
28.3    33
26.5    33
28.2    33
22.1    33
23.6    32
27.3    31
21.0    30
21.3    30
22.7    30
21.5    29
23.1    28
20.8    28
22.3    27
24.0    27
27.5    26
29.0    26
22.5    26
23.8    25
24.8    25
22.8    24
22.6    24
22.4    23
23.3    23
30.7    23
22.0    23
29.3    23
31.6    22
21.9    22
23.2    22
31.9    22
32.3    22
20.4    22
26.4    21
28.7    21
30.0    21
20.1    20
30.9    19
22.9    19
Name: BMI, dtype: int64

In [9]:

subset2 = subset_nomiss[subset_nomiss.Immuno == 2]
subset2.count()

new.ID          262
time            262
Age             262
Gender          262
Race            262
Urban           262
Immuno          262
Chronic         262
Smoker          262
Drinker         262
Mod Post hrs    262
BDI Total       262
BAI Total       262
BMI             262
dtype: int64

PCA
SVM
Perceptron
MLP
Neural Networks
Convolutional Neural Networks
Recurrent Neural Networks
k Nearest Neighbors
weighted k Nearest Neighbors
decision tree
random forest

While looking at the baselines we can see that some people claimed to have reported weakened immune systems, while looking at who in the data set reported a weakened immune system we can predict who else might be at risk of having one.

This will be done by setting the target variable to Immuno which have values 1 2 and 3.
1. previously diagnosed immune issue
2. current immune issue
3. never had immune issues

After classifying we can look into what

In [10]:
predictors = ['Age', 'Chronic', 'Smoker', 'Drinker', 'Urban', 'BDI Total', 'BAI Total', 'Gender']
target = 'Immuno'
train_data, test_data, train_sln, test_sln = train_test_split(subset_nomiss[predictors], subset_nomiss[target], test_size = 0.2, random_state=41)
train_data

       Age  Chronic  Smoker  Drinker  Urban  BDI Total  BAI Total  Gender
2347   5.0      2.0     2.0      2.0    1.0          9          5     2.0
11635  6.0      3.0     2.0      1.0    2.0          4          0     1.0
22915  2.0      3.0     2.0      1.0    2.0          6         25     2.0
8385   4.0      3.0     2.0      2.0    2.0         11         10     2.0
178    1.0      3.0     2.0      1.0    2.0         11          7     1.0
...    ...      ...     ...      ...    ...        ...        ...     ...
1749   6.0      3.0     2.0      1.0    2.0          3          0     1.0
2335   1.0      3.0     2.0      1.0    3.0         16         28     2.0
8368   6.0      3.0     2.0      1.0    1.0          2          1     2.0
6949   1.0      2.0     2.0      2.0    2.0         20         16     2.0
15240  3.0      2.0     2.0      2.0    2.0          8          0     1.0

[2470 rows x 8 columns]

In [11]:
import numpy as np

print(np.isinf(train_data))

train_data = np.nan_to_num(train_data)

print(np.isinf(train_data))

         Age  Chronic  Smoker  Drinker  Urban  BDI Total  BAI Total  Gender
2347   False    False   False    False  False      False      False   False
11635  False    False   False    False  False      False      False   False
22915  False    False   False    False  False      False      False   False
8385   False    False   False    False  False      False      False   False
178    False    False   False    False  False      False      False   False
...      ...      ...     ...      ...    ...        ...        ...     ...
1749   False    False   False    False  False      False      False   False
2335   False    False   False    False  False      False      False   False
8368   False    False   False    False  False      False      False   False
6949   False    False   False    False  False      False      False   False
15240  False    False   False    False  False      False      False   False

[2470 rows x 8 columns]
[[False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]
 ...
 [False False False ... False False False]
 [False False False ... False False False]
 [False False False ... False False False]]

In [12]:
from sklearn.metrics import accuracy_score

scaler = StandardScaler()
scaler.fit(train_data)
scaler.fit(test_data)
test_scaled = scaler.fit_transform(test_data)

train_scaled = scaler.fit_transform(train_data)

from sklearn import tree
from sklearn import metrics

dt = tree.DecisionTreeClassifier(max_depth = 40, random_state = 1, class_weight='balanced')

dt.fit(train_data,train_sln)

immuno_pred = dt.predict(test_data)

print("Unnormalized data results")
accuracy = accuracy_score(immuno_pred, test_sln)

# Print the accuracy score
print('Accuracy:', accuracy)

train_sln.value_counts()
test_sln.value_counts()

Unnormalized data results
Accuracy: 0.8058252427184466

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but DecisionTreeClassifier was fitted without feature names
  warnings.warn(

3.0    560
2.0     48
1.0     10
Name: Immuno, dtype: int64

In [13]:
knn = neighbors.KNeighborsClassifier(n_neighbors=10, weights = 'uniform')

knn.fit(train_scaled, train_sln)

preds = knn.predict(test_scaled)
print("Unnormalized data results")
acc = accuracy_score(immuno_pred, test_sln)

# Print the accuracy score
print('Accuracy:', acc)
test_scaled

Unnormalized data results
Accuracy: 0.8058252427184466

array([[ 1.680022  , -2.73240097,  0.15772007, ..., -0.8206978 ,
        -0.83201869,  0.78975027],
       [-0.41323122, -1.01457411,  0.15772007, ...,  0.46718393,
         1.10511359,  0.78975027],
       [ 0.63339539,  0.70325274,  0.15772007, ...,  0.8184244 ,
        -0.34773562, -1.18622409],
       ...,
       [ 1.680022  ,  0.70325274,  0.15772007, ..., -0.8206978 ,
        -0.46880638,  0.78975027],
       [-0.41323122, -1.01457411,  0.15772007, ...,  0.58426409,
         2.07367973, -1.18622409],
       [ 1.1567087 , -2.73240097,  0.15772007, ..., -0.8206978 ,
        -0.58987715, -1.18622409]])

In [14]:
knn = neighbors.KNeighborsClassifier(n_neighbors=10, weights = 'uniform')

knn.fit(train_scaled, train_sln)

preds = knn.predict(test_scaled)
print("Unnormalized data results")
acc2 = accuracy_score(immuno_pred, test_sln)

# Print the accuracy score
print('Accuracy:', acc2)
test_scaled
print(test_sln.iloc[7])
print(preds)
test_sln.head(45)

Unnormalized data results
Accuracy: 0.8058252427184466
3.0
[2. 2. 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 2. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 2. 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 2.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 2. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]

11400    3.0
22679    3.0
16674    3.0
15877    3.0
22989    3.0
20178    3.0
6258     3.0
12309    3.0
11774    3.0
7661     3.0
10311    3.0
9089     3.0
133      3.0
6794     3.0
23243    3.0
17680    3.0
8886     3.0
2854     3.0
17703    3.0
17652    1.0
4577     3.0
17736    3.0
8841     3.0
20038    3.0
19437    3.0
11713    3.0
11722    3.0
17499    3.0
5854     3.0
573      3.0
3854     3.0
22245    3.0
15934    3.0
6128     2.0
9483     3.0
3730     3.0
17614    3.0
1685     2.0
15031    2.0
15503    3.0
2615     3.0
24307    3.0
17165    3.0
17416    3.0
11362    2.0
Name: Immuno, dtype: float64

In [15]:
from sklearn.feature_selection import SelectKBest
selector = SelectKBest(k=2)
selector.fit(train_data,train_sln)

# bigger number means the feature is more important
print('Here are the scores of each feature:')
print(selector.scores_)
print(predictors)

Here are the scores of each feature:
[2.04776198e+01 1.19991384e+02 3.57566913e-02 2.77204967e+00
 8.45547796e-01 2.04342775e+00 6.07824461e+00 3.98161523e+00]
['Age', 'Chronic', 'Smoker', 'Drinker', 'Urban', 'BDI Total', 'BAI Total', 'Gender']

In [35]:
sub2_health = health[['new.ID', 'time', 'Age', 'Gender', 'Urban', 'Immuno', 'Chronic', 'Smoker', 'BDI Total', 'BAI Total', 'COV_iso_guide']]

sub2_health.count()


health3 = sub2_health[sub2_health.time == 'baseline']

sub3 = health3[health3.COV_iso_guide.notnull()]
sub3

sub3.COV_iso_guide.value_counts()

4.0        29
2.0        26
12345.0    19
3.0        15
123.0      13
1.0        12
5.0        11
24.0       10
13.0        6
1235.0      6
35.0        4
25.0        4
12.0        4
245.0       3
135.0       3
125.0       3
45.0        2
134.0       1
15.0        1
1234.0      1
Name: COV_iso_guide, dtype: int64

In [72]:
from sklearn.model_selection import train_test_split

npredictors = ['Age', 'Chronic', 'Immuno', 'Smoker', 'Gender']
ntarget = 'COV_iso_guide'
ntrain_data, ntest_data, ntrain_sln, ntest_sln = train_test_split(sub3[npredictors], sub3[ntarget], test_size = 0.1, random_state=41)
ntrain_data
ntest_sln

18689       24.0
9491         4.0
4971         2.0
18825       15.0
17880      245.0
22809        2.0
7081        25.0
2175      1235.0
22988        5.0
22339        3.0
15863        5.0
4871        12.0
19179        4.0
14798       35.0
693          4.0
2321         2.0
21962    12345.0
5736     12345.0
Name: COV_iso_guide, dtype: float64

In [73]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model2 = Sequential() 
#build your model here:
model2.add(Dense(128, activation='relu', input_dim=8))
model2.add(Dense(1, activation='sigmoid')) # binary classification 
model2.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy']) 
model2.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_30 (Dense)            (None, 128)               1152

 dense_31 (Dense)            (None, 1)                 129

=================================================================
Total params: 1,281
Trainable params: 1,281
Non-trainable params: 0
_________________________________________________________________

In [74]:
model2.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [75]:
hist2 = model2.fit(ntrain_data, ntrain_sln, validation_data=(ntest_data, ntest_sln), epochs=10, batch_size=1)

Epoch 1/10

ValueError: ignored

In [76]:
from keras.models import Sequential
from keras.layers import Dense

# Initialize the model
model = Sequential()

# Add the input layer and first hidden layer
model.add(Dense(1, activation='relu', input_dim=8))

# Add additional hidden layers
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))

# Add the output layer
model.add(Dense(1, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [77]:
hist2 = model.fit(ntrain_data, ntrain_sln, validation_data=(ntest_data, ntest_sln), epochs=10, batch_size=100)

Epoch 1/10

ValueError: ignored

In [82]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators=25)
forest.fit(ntrain_data, ntrain_sln)
covpreds = forest.predict(ntest_data)

new_preds = forest.predict(ntest_data)
print("Forest data results")
acc3 = accuracy_score(covpreds, ntest_sln)
print(acc3)

print(covpreds)
print(ntest_sln)
print(ntest_data.Gender)

Forest data results
0.1111111111111111
[1.2300e+02 1.2350e+03 4.0000e+00 4.0000e+00 4.0000e+00 1.2345e+04
 4.0000e+00 4.0000e+00 2.0000e+00 3.0000e+00 4.0000e+00 1.2345e+04
 2.0000e+00 1.2300e+02 5.0000e+00 2.4000e+01 2.4000e+01 1.2345e+04]
18689       24.0
9491         4.0
4971         2.0
18825       15.0
17880      245.0
22809        2.0
7081        25.0
2175      1235.0
22988        5.0
22339        3.0
15863        5.0
4871        12.0
19179        4.0
14798       35.0
693          4.0
2321         2.0
21962    12345.0
5736     12345.0
Name: COV_iso_guide, dtype: float64
18689    1.0
9491     1.0
4971     1.0
18825    2.0
17880    2.0
22809    2.0
7081     1.0
2175     1.0
22988    2.0
22339    2.0
15863    2.0
4871     1.0
19179    2.0
14798    1.0
693      2.0
2321     2.0
21962    2.0
5736     2.0
Name: Gender, dtype: float64

In [81]:
selector = SelectKBest(k=2)
selector.fit(ntrain_data, ntrain_sln)

# bigger number means the feature is more important
print('Here are the scores of each feature:')
print(selector.scores_)
print(npredictors)

Here are the scores of each feature:
[0.88075787 0.691129   1.54226197 1.46649657 1.7592564 ]
['Age', 'Chronic', 'Immuno', 'Smoker', 'Gender']